import $ from './core';
import './modules/display';
import './modules/classes';
import './modules/handlers';
import './modules/actions';
import './modules/effects';
import './components/dropdown';
import './components/drop';
import './components/modals';
import './components/modal';
import './components/tab';
import './components/accordion';
import './components/carousel';
import './components/sliders';
import './components/burger';
import './components/calc';
import './components/checkTextInputs';
import './components/showInfo';
import './components/showMoreStyles';
import './components/difference';
import './components/filter';
import './components/form';
import './components/forms';
import './components/mask';
import './components/pictureSize';
import './components/playVideo';
import './components/scrolling';
import './services/requests';

export default $;